package main

// Player to Server packet types
const (
	PLI_LEVELWARP = iota
	PLI_BOARDMODIFY
	PLI_PLAYERPROPS
	PLI_NPCPROPS
	PLI_BOMBADD
	PLI_BOMBDEL
	PLI_TOALL
	PLI_HORSEADD
	PLI_HORSEDEL
	PLI_ARROWADD
	PLI_FIRESPY
	PLI_THROWCARRIED
	PLI_ITEMADD
	PLI_ITEMDEL
	PLI_CLAIMPKER
	PLI_BADDYPROPS
	PLI_BADDYHURT
	PLI_BADDYADD
	PLI_FLAGSET
	PLI_FLAGDEL
	PLI_OPENCHEST
	PLI_PUTNPC
	PLI_NPCDEL
	PLI_WANTFILE
	PLI_SHOWIMG
	PLI_UNKNOWN25
	PLI_HURTPLAYER
	PLI_EXPLOSION
	PLI_PRIVATEMESSAGE
	PLI_NPCWEAPONDEL
	PLI_LEVELWARPMOD
	PLI_PACKETCOUNT
	PLI_ITEMTAKE
	PLI_WEAPONADD
	PLI_UPDATEFILE
	PLI_ADJACENTLEVEL
	PLI_HITOBJECTS
	PLI_LANGUAGE
	PLI_TRIGGERACTION
	PLI_MAPINFO
	PLI_SHOOT
	PLI_SERVERWARP
	_
	PLI_MUTEPLAYER
	PLI_PROCESSLIST
	_
	PLI_UNKNOWN46
	PLI_VERIFYWANTSEND
	PLI_SHOOT2
	_
	PLI_RAWDATA
	PLI_RC_SERVEROPTIONSGET
	PLI_RC_SERVEROPTIONSSET
	PLI_RC_FOLDERCONFIGGET
	PLI_RC_FOLDERCONFIGSET
	PLI_RC_RESPAWNSET
	PLI_RC_HORSELIFESET
	PLI_RC_APINCREMENTSET
	PLI_RC_BADDYRESPAWNSET
	PLI_RC_PLAYERPROPSGET
	PLI_RC_PLAYERPROPSSET
	PLI_RC_DISCONNECTPLAYER
	PLI_RC_UPDATELEVELS
	PLI_RC_ADMINMESSAGE
	PLI_RC_PRIVADMINMESSAGE
	PLI_RC_LISTRCS
	PLI_RC_DISCONNECTRC
	PLI_RC_APPLYREASON
	PLI_RC_SERVERFLAGSGET
	PLI_RC_SERVERFLAGSSET
	PLI_RC_ACCOUNTADD
	PLI_RC_ACCOUNTDEL
	PLI_RC_ACCOUNTLISTGET
	PLI_RC_PLAYERPROPSGET2
	PLI_RC_PLAYERPROPSGET3
	PLI_RC_PLAYERPROPSRESET
	PLI_RC_PLAYERPROPSSET2
	PLI_RC_ACCOUNTGET
	PLI_RC_ACCOUNTSET
	PLI_RC_CHAT
	PLI_PROFILEGET
	PLI_PROFILESET
	PLI_RC_WARPPLAYER
	PLI_RC_PLAYERRIGHTSGET
	PLI_RC_PLAYERRIGHTSSET
	PLI_RC_PLAYERCOMMENTSGET
	PLI_RC_PLAYERCOMMENTSSET
	PLI_RC_PLAYERBANGET
	PLI_RC_PLAYERBANSET
	PLI_RC_FILEBROWSER_START
	PLI_RC_FILEBROWSER_CD
	PLI_RC_FILEBROWSER_END
	PLI_RC_FILEBROWSER_DOWN
	PLI_RC_FILEBROWSER_UP
	PLI_NPCSERVERQUERY
	PLI_RC_LARGEFILESTART
	PLI_RC_LARGEFILEEND
	PLI_RC_FILEBROWSER_MOVE
	PLI_RC_FILEBROWSER_DELETE
	PLI_RC_FILEBROWSER_RENAME
	_
	_
	_
	_
	PLI_NC_NPCGET
	PLI_NC_NPCDELETE
	PLI_NC_NPCRESET
	PLI_NC_NPCSCRIPTGET
	PLI_NC_NPCWARP
	PLI_NC_NPCFLAGSGET
	PLI_NC_NPCSCRIPTSET
	PLI_NC_NPCFLAGSSET
	PLI_NC_NPCADD
	PLI_NC_CLASSEDIT
	PLI_NC_CLASSADD
	PLI_NC_LOCALNPCSGET
	PLI_NC_WEAPONLISTGET
	PLI_NC_WEAPONGET
	PLI_NC_WEAPONADD
	PLI_NC_WEAPONDELETE
	PLI_NC_CLASSDELETE
	_
	_
	_
	_
	_
	_
	_
	_
	PLI_REQUESTUPDATEBOARD
	_
	_
	PLI_NC_LEVELLISTGET
	PLI_NC_LEVELLISTSET
	PLI_REQUESTTEXT
	PLI_SENDTEXT
	_
	PLI_UPDATEGANI
	PLI_UPDATESCRIPT
	PLI_UPDATEPACKAGEREQUESTFILE
	PLI_RC_FOLDERDELETE
	PLI_UPDATECLASS
	PLI_RC_UNKNOWN162
)

// Server to Player packet types
const (
	PLO_LEVELBOARD = iota
	PLO_LEVELLINK
	PLO_BADDYPROPS
	PLO_NPCPROPS
	PLO_LEVELCHEST
	PLO_LEVELSIGN
	PLO_LEVELNAME
	PLO_BOARDMODIFY
	PLO_OTHERPLPROPS
	PLO_PLAYERPROPS
	PLO_ISLEADER
	PLO_BOMBADD
	PLO_BOMBDEL
	PLO_TOALL
	PLO_PLAYERWARP
	PLO_WARPFAILED
	PLO_DISCMESSAGE
	PLO_HORSEADD
	PLO_HORSEDEL
	PLO_ARROWADD
	PLO_FIRESPY
	PLO_THROWCARRIED
	PLO_ITEMADD
	PLO_ITEMDEL
	PLO_NPCMOVED
	PLO_SIGNATURE
	PLO_NPCACTION
	PLO_BADDYHURT
	PLO_FLAGSET
	PLO_NPCDEL
	PLO_FILESENDFAILED
	PLO_FLAGDEL
	PLO_SHOWIMG
	PLO_NPCWEAPONADD
	PLO_NPCWEAPONDEL
	PLO_RC_ADMINMESSAGE
	PLO_EXPLOSION
	PLO_PRIVATEMESSAGE
	PLO_PUSHAWAY
	PLO_LEVELMODTIME
	PLO_HURTPLAYER
	PLO_STARTMESSAGE
	PLO_NEWWORLDTIME
	PLO_DEFAULTWEAPON
	PLO_HASNPCSERVER
	PLO_FILEUPTODATE
	PLO_HITOBJECTS
	PLO_STAFFGUILDS
	PLO_TRIGGERACTION
	PLO_PLAYERWARP2
	PLO_RC_ACCOUNTADD
	PLO_RC_ACCOUNTSTATUS
	PLO_RC_ACCOUNTNAME
	PLO_RC_ACCOUNTDEL
	PLO_RC_ACCOUNTPROPS
	PLO_ADDPLAYER
	PLO_DELPLAYER
	PLO_RC_ACCOUNTPROPSGET
	PLO_RC_ACCOUNTCHANGE
	PLO_RC_PLAYERPROPSCHANGE
	PLO_UNKNOWN60
	PLO_RC_SERVERFLAGSGET
	PLO_RC_PLAYERRIGHTSGET
	PLO_RC_PLAYERCOMMENTSGET
	PLO_RC_PLAYERBANGET
	PLO_RC_FILEBROWSER_DIRLIST
	PLO_RC_FILEBROWSER_DIR
	PLO_RC_FILEBROWSER_MESSAGE
	PLO_LARGEFILESTART
	PLO_LARGEFILEEND
	PLO_RC_ACCOUNTLISTGET
	PLO_RC_PLAYERPROPS
	PLO_RC_PLAYERPROPSGET
	PLO_RC_ACCOUNTGET
	PLO_RC_CHAT
	PLO_PROFILE
	PLO_RC_SERVEROPTIONSGET
	PLO_RC_FOLDERCONFIGGET
	PLO_NC_CONTROL
	PLO_NPCSERVERADDR
	PLO_NC_LEVELLIST
	PLO_UNKNOWN81
	PLO_SERVERTEXT
	PLO_UNKNOWN83
	PLO_LARGEFILESIZE
	PLO_RAWDATA
	PLO_BOARDPACKET
	PLO_FILE
	PLO_RC_MAXUPLOADFILESIZE
	PLO_UNKNOWN104
	PLO_UPDATEPACKAGESIZE
	PLO_UPDATEPACKAGEDONE
	PLO_BOARDLAYER
	PLO_UNKNOWN109
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	PLO_UNKNOWN124
	PLO_NPCBYTECODE
	PLO_UNKNOWN132
	PLO_UNKNOWN133
	PLO_GANISCRIPT
	PLO_NPCWEAPONSCRIPT
	_
	_
	_
	_
	_
	_
	_
	PLO_NPCDEL2
	PLO_HIDENPCS
	PLO_SAY2
	PLO_FREEZEPLAYER2
	PLO_UNFREEZEPLAYER
	PLO_SETACTIVELEVEL
	PLO_NC_NPCATTRIBUTES
	PLO_NC_NPCADD
	PLO_NC_NPCDELETE
	PLO_NC_NPCSCRIPT
	PLO_NC_NPCFLAGS
	PLO_NC_CLASSGET
	PLO_NC_CLASSADD
	PLO_NC_LEVELDUMP
	PLO_MOVE
	PLO_UNKNOWN166
	PLO_NC_WEAPONLISTGET
	PLO_UNKNOWN168
	PLO_UNKNOWN169
	PLO_GHOSTMODE
	PLO_BIGMAP
	PLO_MINIMAP
	PLO_GHOSTTEXT
	PLO_GHOSTICON
	PLO_SHOOT
	PLO_FULLSTOP
	PLO_FULLSTOP2
	PLO_SERVERWARP
	PLO_RPGWINDOW
	PLO_STATUSLIST
	PLO_UNKNOWN181
	PLO_LISTPROCESSES
	PLO_UNKNOWN183
	PLO_UNKNOWN184
	PLO_UNKNOWN185
	PLO_UNKNOWN186
	PLO_UPDATEPACKAGEISUPDATED
	PLO_NC_CLASSDELETE
	PLO_MOVE2
	PLO_UNKNOWN190
	PLO_SHOOT2
	PLO_NC_WEAPONGET
	PLO_UNKNOWN193
	PLO_CLEARWEAPONS
	PLO_UNKNOWN195
)

// Server to List Server packet types
const (
	SVO_SETNAME = iota
	SVO_SETDESC
	SVO_SETLANG
	SVO_SETVERS
	SVO_SETURL
	SVO_SETIP
	SVO_SETPORT
	SVO_SETPLYR
	SVO_VERIACC
	SVO_VERIGUILD
	SVO_GETFILE
	SVO_NICKNAME
	SVO_GETPROF
	SVO_SETPROF
	SVO_PLYRADD
	SVO_PLYRREM
	SVO_PING
	SVO_VERIACC2
	SVO_SETLOCALIP
	SVO_GETFILE2
	SVO_UPDATEFILE
	SVO_GETFILE3
	SVO_NEWSERVER
	SVO_SERVERHQPASS
	SVO_SERVERHQLEVEL
	SVO_SERVERINFO
	SVO_REQUESTLIST
	SVO_REQUESTSVRINFO
	SVO_REQUESTBUDDIES
	SVO_PMPLAYER
	SVO_REGISTERV3
	SVO_SENDTEXT
	SVO_PACKETCOUNT
)

// List Server to Server packet types
const (
	SVI_VERIACC = iota
	SVI_VERIGUILD
	SVI_FILESTART
	SVI_FILEEND
	SVI_FILEDATA
	SVI_VERSIONOLD
	SVI_VERSIONCURRENT
	SVI_PROFILE
	SVI_ERRMSG
	SVI_NULL4
	SVI_NULL5
	SVI_VERIACC2
	SVI_FILESTART2
	SVI_FILEDATA2
	SVI_FILEEND2
	SVI_FILESTART3
	SVI_FILEDATA3
	SVI_FILEEND3
	SVI_SERVERINFO
	SVI_REQUESTTEXT
	SVI_SENDTEXT
	_
	_
	_
	SVI_PMPLAYER
	SVI_ASSIGNPCID
	SVI_PING
	SVI_RAWDATA
	SVI_PACKETCOUNT
)

// Player flags
const (
	PLFLAG_NOMASSMESSAGE  = 0x01
	PLFLAG_ONLYSHOWONELEVEL = 0x02
	PLFLAG_NOTOALL        = 0x04
	PLFLAG_VOICEDISABLED  = 0x08
)

// Player status flags
const (
	PLSTATUS_PAUSED      = 0x01
	PLSTATUS_HIDDEN      = 0x02
	PLSTATUS_MALE        = 0x04
	PLSTATUS_DEAD        = 0x08
	PLSTATUS_ALLOWWEAPONS = 0x10
	PLSTATUS_HIDESWORD   = 0x20
	PLSTATUS_HASSPIN     = 0x40
)

// Player type flags
const (
	PLTYPE_AWAIT      = -1
	PLTYPE_CLIENT     = 1
	PLTYPE_RC         = 2
	PLTYPE_NPCSERVER  = 4
	PLTYPE_NC         = 8
	PLTYPE_CLIENT2    = 16
	PLTYPE_CLIENT3    = 32
	PLTYPE_RC2        = 64
	PLTYPE_EXTERNAL   = 128
	PLTYPE_WEB        = 256
)

// Combinations for easier checking
const (
	PLTYPE_ANYCLIENT  = PLTYPE_CLIENT | PLTYPE_CLIENT2 | PLTYPE_CLIENT3 | PLTYPE_WEB
	PLTYPE_ANYRC      = PLTYPE_RC | PLTYPE_RC2
	PLTYPE_ANYNC      = PLTYPE_NC
	PLTYPE_ANYCONTROL = PLTYPE_ANYRC | PLTYPE_ANYNC
	PLTYPE_ANYPLAYER  = PLTYPE_ANYCLIENT | PLTYPE_ANYRC
	PLTYPE_NONITERABLE = PLTYPE_NPCSERVER | PLTYPE_ANYNC | PLTYPE_EXTERNAL
)

// Player property indices (from Account.h)
const (
	PLPROP_NICKNAME = iota
	PLPROP_MAXPOWER
	PLPROP_CURPOWER
	PLPROP_RUPEESCOUNT
	PLPROP_ARROWSCOUNT
	PLPROP_BOMBSCOUNT
	PLPROP_GLOVEPOWER
	PLPROP_BOMBPOWER
	PLPROP_SWORDPOWER
	PLPROP_SHIELDPOWER
	PLPROP_GANI
	PLPROP_HEADGIF
	PLPROP_CURCHAT
	PLPROP_COLORS
	PLPROP_ID
	PLPROP_X
	PLPROP_Y
	PLPROP_SPRITE
	PLPROP_STATUS
	PLPROP_CARRYSPRITE
	PLPROP_CURLEVEL
	PLPROP_HORSEGIF
	PLPROP_HORSEBUSHES
	PLPROP_EFFECTCOLORS
	PLPROP_CARRYNPC
	PLPROP_APCOUNTER
	PLPROP_MAGICPOINTS
	PLPROP_KILLSCOUNT
	PLPROP_DEATHSCOUNT
	PLPROP_ONLINESECS
	PLPROP_IPADDR
	PLPROP_UDPPORT
	PLPROP_ALIGNMENT
	PLPROP_ADDITFLAGS
	PLPROP_ACCOUNTNAME
	PLPROP_BODYIMG
	PLPROP_RATING
	PLPROP_GATTRIB1
	PLPROP_GATTRIB2
	PLPROP_GATTRIB3
	PLPROP_GATTRIB4
	PLPROP_GATTRIB5
	PLPROP_ATTACHNPC
	PLPROP_GMAPLEVELX
	PLPROP_GMAPLEVELY
	PLPROP_Z
	PLPROP_GATTRIB6
	PLPROP_GATTRIB7
	PLPROP_GATTRIB8
	PLPROP_GATTRIB9
	PLPROP_JOINLEAVELVL
	PLPROP_PCONNECTED
	PLPROP_PLANGUAGE
	PLPROP_PSTATUSMSG
	PLPROP_GATTRIB10
	PLPROP_GATTRIB11
	PLPROP_GATTRIB12
	PLPROP_GATTRIB13
	PLPROP_GATTRIB14
	PLPROP_GATTRIB15
	PLPROP_GATTRIB16
	PLPROP_GATTRIB17
	PLPROP_GATTRIB18
	PLPROP_GATTRIB19
	PLPROP_GATTRIB20
	PLPROP_GATTRIB21
	PLPROP_GATTRIB22
	PLPROP_GATTRIB23
	PLPROP_GATTRIB24
	PLPROP_GATTRIB25
	PLPROP_GATTRIB26
	PLPROP_GATTRIB27
	PLPROP_GATTRIB28
	PLPROP_GATTRIB29
	PLPROP_GATTRIB30
	PLPROP_OSTYPE
	PLPROP_TEXTCODEPAGE
	PLPROP_UNKNOWN77
	PLPROP_X2
	PLPROP_Y2
	PLPROP_Z2
	PLPROP_UNKNOWN81
	PLPROP_COMMUNITYNAME
)

const PROPCOUNT = 83

// Admin permissions
const (
	PLPERM_WARPTO = 1 << iota
	PLPERM_WARPTOPLAYER
	PLPERM_SUMMON
	PLPERM_UPDATELEVEL
	PLPERM_DISCONNECT
	PLPERM_VIEWATTRIBUTES
	PLPERM_SETATTRIBUTES
	PLPERM_SETSELFATTRIBUTES
	PLPERM_RESETATTRIBUTES
	PLPERM_ADMINMSG
	PLPERM_SETRIGHTS
	PLPERM_BAN
	PLPERM_SETCOMMENTS
	PLPERM_INVISIBLE
	PLPERM_MODIFYSTAFFACCOUNT
	PLPERM_SETSERVERFLAGS
	PLPERM_SETSERVEROPTIONS
	PLPERM_SETFOLDEROPTIONS
	PLPERM_SETFOLDERRIGHTS
	PLPERM_NPCCONTROL
)

// NPC property indices
const (
	NPCPROP_IMAGE = iota
	NPCPROP_SCRIPT
	NPCPROP_X
	NPCPROP_Y
	NPCPROP_POWER
	NPCPROP_RUPEES
	NPCPROP_ARROWS
	NPCPROP_BOMBS
	NPCPROP_GLOVEPOWER
	NPCPROP_BOMBPOWER
	NPCPROP_SWORDIMAGE
	NPCPROP_SHIELDIMAGE
	NPCPROP_GANI
	NPCPROP_VISFLAGS
	NPCPROP_BLOCKFLAGS
	NPCPROP_MESSAGE
	NPCPROP_HURTDXDY
	NPCPROP_ID
	NPCPROP_SPRITE
	NPCPROP_COLORS
	NPCPROP_NICKNAME
	NPCPROP_HORSEIMAGE
	NPCPROP_HEADIMAGE
	NPCPROP_SAVE0
	NPCPROP_SAVE1
	NPCPROP_SAVE2
	NPCPROP_SAVE3
	NPCPROP_SAVE4
	NPCPROP_SAVE5
	NPCPROP_SAVE6
	NPCPROP_SAVE7
	NPCPROP_SAVE8
	NPCPROP_SAVE9
	NPCPROP_ALIGNMENT
	NPCPROP_IMAGEPART
	NPCPROP_BODYIMAGE
	NPCPROP_GATTRIB1
	NPCPROP_GATTRIB2
	NPCPROP_GATTRIB3
	NPCPROP_GATTRIB4
	NPCPROP_GATTRIB5
	NPCPROP_GMAPLEVELX
	NPCPROP_GMAPLEVELY
	NPCPROP_Z
	NPCPROP_GATTRIB6
	NPCPROP_GATTRIB7
	NPCPROP_GATTRIB8
	NPCPROP_GATTRIB9
	NPCPROP_UNKNOWN48
	NPCPROP_SCRIPTER
	NPCPROP_NAME
	NPCPROP_TYPE
	NPCPROP_CURLEVEL
	NPCPROP_GATTRIB10
	NPCPROP_GATTRIB11
	NPCPROP_GATTRIB12
	NPCPROP_GATTRIB13
	NPCPROP_GATTRIB14
	NPCPROP_GATTRIB15
	NPCPROP_GATTRIB16
	NPCPROP_GATTRIB17
	NPCPROP_GATTRIB18
	NPCPROP_GATTRIB19
	NPCPROP_GATTRIB20
	NPCPROP_GATTRIB21
	NPCPROP_GATTRIB22
	NPCPROP_GATTRIB23
	NPCPROP_GATTRIB24
	NPCPROP_GATTRIB25
	NPCPROP_GATTRIB26
	NPCPROP_GATTRIB27
	NPCPROP_GATTRIB28
	NPCPROP_GATTRIB29
	NPCPROP_GATTRIB30
	NPCPROP_CLASS
	NPCPROP_X2
	NPCPROP_Y2
	NPCPROP_Z2
)

// NPC visibility flags
const (
	NPCVISFLAG_VISIBLE        = 0x01
	NPCVISFLAG_DRAWOVERPLAYER = 0x02
	NPCVISFLAG_DRAWUNDERPLAYER = 0x04
)

// NPC block flags
const (
	NPCBLOCKFLAG_BLOCK   = 0x00
	NPCBLOCKFLAG_NOBLOCK = 0x01
)

// NPC type
type NPCType int

const (
	LEVELNPC NPCType = iota
	PUTNPC
	DBNPC
)

// Socket type
const (
	SOCK_PLAYER = 0
	SOCK_SERVER = 1
)

// File system types
const (
	FS_ALL = iota
	FS_FILE
	FS_LEVEL
	FS_HEAD
	FS_BODY
	FS_SWORD
	FS_SHIELD
)

const FSCOUNT = 7

// Initial ID values
const (
	PLAYERID_INIT = 2
	NPCID_INIT     = 10001
	EXTERNALPLAYERID_INIT = 16000
	BADDYID_INIT   = 1
)

// Server file types (for list server)
const (
	SVF_HEAD = iota
	SVF_BODY
	SVF_SWORD
	SVF_SHIELD
	SVF_FILE
)
